In [2]:
%config IPCompleter.greedy=True
import numpy as np

In [3]:
b = np.array([[0,-1,2],[1,0,-3],[-2,3,0]])

In [4]:
b

array([[ 0, -1,  2],
       [ 1,  0, -3],
       [-2,  3,  0]])

In [5]:
i = np.identity(3, dtype = int)

In [6]:
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
iminusb = i - b

In [8]:
iminusb = np.asmatrix(iminusb)


In [9]:
iplusb = i + b
print(iplusb)

[[ 1 -1  2]
 [ 1  1 -3]
 [-2  3  1]]


In [10]:
np.linalg.det(iminusb)

15.000000000000007

In [11]:
iplusb=np.asmatrix(iplusb)

In [12]:
iminusb

matrix([[ 1,  1, -2],
        [-1,  1,  3],
        [ 2, -3,  1]])

In [13]:
iminusbinverse = np.linalg.inv(iminusb)

In [14]:
iminusbinverse

matrix([[ 0.66666667,  0.33333333,  0.33333333],
        [ 0.46666667,  0.33333333, -0.06666667],
        [ 0.06666667,  0.33333333,  0.13333333]])

In [15]:
A = iplusb * iminusbinverse

In [16]:
A

matrix([[ 0.33333333,  0.66666667,  0.66666667],
        [ 0.93333333, -0.33333333, -0.13333333],
        [ 0.13333333,  0.66666667, -0.73333333]])

In [17]:
A.getI()

matrix([[ 0.33333333,  0.93333333,  0.13333333],
        [ 0.66666667, -0.33333333,  0.66666667],
        [ 0.66666667, -0.13333333, -0.73333333]])

In [18]:
A.transpose()

matrix([[ 0.33333333,  0.93333333,  0.13333333],
        [ 0.66666667, -0.33333333,  0.66666667],
        [ 0.66666667, -0.13333333, -0.73333333]])

In [19]:
A.getI() == A.transpose()

matrix([[False,  True, False],
        [ True, False, False],
        [False, False, False]])

In [20]:
eig = np.array([[0,1,0],[1,0,1],[0,1,0]])

In [21]:
eig

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [22]:
np.linalg.det(eig)

0.0

In [23]:
yay = np.array([[3,2,2], [2,3,2]])
print(yay)

[[3 2 2]
 [2 3 2]]


In [24]:
yayt = yay.transpose()

In [26]:
yayt

array([[3, 2],
       [2, 3],
       [2, 2]])

In [29]:
yay = np.asmatrix(yay)

In [30]:
yayt = np.asmatrix(yayt)

In [31]:
j = yayt*yay

In [32]:
j

matrix([[13, 12, 10],
        [12, 13, 10],
        [10, 10,  8]])

In [ ]:
w, v = np.linalg.eig(j)

In [ ]:
w

In [ ]:
v